In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from WindPy import w
w.start()

.ErrorCode=-40520005
.Data=[No Python API Authority!]

In [2]:
bond = w.edb("M0265799","2016-01-01","2026-01-27")
bond_df = pd.DataFrame(bond.Data, index=['中债综合全价总值指数'], columns=bond.Times).T
bond_df

Empty DataFrame
Columns: [中债综合全价总值指数]
Index: []

In [3]:
# M0071618上一期是0.3知道2015-10-31
deposit = w.edb("M0071618","2016-01-01","2026-01-27","Fill=Previous")
deposit_df = pd.DataFrame(deposit.Data, index=['银行活期存款利率'], columns=deposit.Times).T
deposit_df

Empty DataFrame
Columns: [银行活期存款利率]
Index: []

In [4]:
data = w.wsd("000300.SH,HSI.HI,SPX.GI,AU9999.SGE","close","2016-01-01","2026-01-27","Currency=CNY")

In [5]:
data_df = pd.DataFrame(data.Data, index=data.Codes, columns=data.Times).T
data_df

Empty DataFrame
Columns: []
Index: []

In [6]:
output = pd.concat([data_df, bond_df], axis=1)
output.to_csv('market_close.csv')

In [7]:
output = pd.concat([data_df, bond_df, deposit_df], axis=1)
output['银行活期存款利率'] = output['银行活期存款利率'].fillna(0.3)
output = output.dropna()

# 年化收益率转日收益率
deposit_series = output['银行活期存款利率'] / 365

output = output.drop(columns=['银行活期存款利率'])
# 计算每日收益率
returns = output.pct_change()
returns = pd.concat([returns, deposit_series], axis=1)
returns = returns.dropna()
returns

Empty DataFrame
Columns: [中债综合全价总值指数, 银行活期存款利率]
Index: []

In [8]:
returns.to_csv('16market_data.csv')